export enum EResponseStatus {
  Ok = 200,
  Created = 201,
  NoContent = 204,

  BadRequest = 400,
  Unauthorized = 401,
  Forbidden = 403,
  NotFound = 404,
  Conflict = 409,
  UnprocessableEntity = 422,

  InternalServerError = 500,
  NotImplemented = 501,
  BadGateway = 502,
  ServiceUnavailable = 503,
}

export enum EErrorCode {
  // Validate header
  MISSING_HEADER_NAMESPACE,
  MISSING_HEADER_APP_CODE,
  MISSING_HEADER_AUTHORIZATION,

  // Validate request
  MISSING_REQUEST_APP_SIGNATURE,

  // Apikey
  APIKEY_UNAUTHORIZATION,
  APIKEY_PAYLOAD_EXTRACT_FAILED,
  APIKEY_PAYLOAD_INVALID,
  APIKEY_PAYLOAD_TYPE_DISMATCH,
  APIKEY_NOT_EXIST,

  // App
  APP_UNAUTHORIZATION,
  APP_NOT_EXIST,
  APP_EXISTED,

  // Config
  CONFIG_NOT_EXIST,
  CONFIG_EXISTED,
  CONFIG_HAVE_NO_ACTIVE,
  CONFIG_HAVE_NO_CHANGES,

  // Webhook
  WEBHOOK_ALREADY_EXIST,
  WEBHOOK_NOT_EXIST,
  WEBHOOK_NOT_OWNED_BY_APP,

  // Webhook History
  WEBHOOK_HISTORY_NOT_EXIST,
  WEBHOOK_HISTORY_RETRY_NOT_ALLOWED,
  WEBHOOK_HISTORY_CALL_ERROR,
  WEBHOOK_HISTORY_METHOD_NOT_SUPPORTED,
  WEBHOOK_HISTORY_BODY_TYPE_NOT_SUPPORTED,
  WEBHOOK_HISTORY_CALL_MISSING_WEBHOOK_SNAPSHORT,

  // Key
  KEY_FILE_NOT_SAVED,
  KEY_NOT_EXIST,
  KEY_SHOULD_REQUEST_NEW,
  KEY_EXPIRED,
  KEY_INVALID_NOT_START,
  KEY_GENERATE_ERROR,
  KEY_GENERATE_ROTATE_MISSING_DURATION,

  // Rate limit
  RATE_LIMIT_REACH,
  RATE_LIMIT_CONFIG_NOT_VALID,

  PUBLIC_KEY_LENGTH_IS_NOT_CONFIGURATED,
  TIME_UNIT_INVALID,
  SORT_FIELD_NOT_SUPPORTED,
  SORT_ORDER_NOT_SUPPORTED,
  API_CALL_ERROR,

  ROUTE_NOT_SUPPORTED = 9998,
  INTERNAL_SERVER = 9999,
  UNKNOWN = 10000,
}
