export const APP_CONSTANTS = {
  DEFAULT_CONFIGS: {
    PUBLIC_KEY_LENGTH: 64,
    WEBHOOK_HISTORY_CLEAN_UP_PERIOD: '1h',
    WEBHOOK_AUTH_HEADER_NAME: 'Authorization',
    WEBHOOK_AUTH_HEADER_FORMAT: 'Apikey {apikey}',
    WEBHOOK_AUTHKEY_ENCRYPT_BYPES: 12,
    WEBHOOK_AUTHKEY_ENCRYPT_SECRET_KEY: 'CFG_KEY_WEBHOOK_AUTHKEY',
    RATE_LIMIT_DURATION: 1,
    RATE_LIMIT_REQUEST: 10,
    API_KEY_GENERATE_DURATION_AMOUNT: 30,
    API_KEY_GENERATE_DURATION_UNIT: 'd',
    WEBHOOK_KEY_DURATION_AMOUNT: 30,
    WEBHOOK_KEY_DURATION_UNIT: 'd',
  },
};
