export const APP_CONSTANTS = {
  FORMATS: {
    keyType: {
      apiKey: (code: string, namespace: string, type: string) => `${code}_${namespace}_${type}`,
      webhook: (type: string, code: string, namespace: string) => `${type}_${code}_${namespace}`,
      config: (appId: string, namespace: string) => `${appId}_${namespace}`,
    },
  },
  DAYJS_MANIPULATE_UNITS: [
    'millisecond',
    'milliseconds',
    'ms',
    'second',
    'seconds',
    's',
    'minute',
    'minutes',
    'm',
    'hour',
    'hours',
    'h',
    'day',
    'days',
    'd',
    'week',
    'weeks',
    'w',
    'month',
    'months',
    'M',
    'year',
    'years',
    'y',
  ] as const,
};
